# Generated by Django 3.1.5 on 2021-01-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20210125_0810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Start',
        ),
    ]
