# Generated by Django 3.1.5 on 2021-01-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210125_0816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Start',
            new_name='Specialty',
        ),
    ]
